version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/nokamoto/webpush-go
    steps:
      - checkout
      - run:
          command: test -z "$(gofmt -l ./*.go)"
      - run:
          name: lint
          command: |
            go get -u golang.org/x/lint/golint
            golint -set_exit_status ./*.go
      - run:
          name: test
          command: |
            go get -u github.com/golang/dep/cmd/dep
            dep ensure -vendor-only=true
            go test .
